version: '3'
services:
  app:
    image: toannvbss/soiot-management:1.0.1
    expose:
      - 3000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
